default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: your_db_username
  password: your_db_password
  host: localhost

development:
  <<: *default
  database: your_db_name_development

test:
  <<: *default
  database: your_db_name_test

production:
  <<: *default
  database: your_production_db_name
  username: <%= ENV['PRODUCTION_DB_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_DB_HOST'] %>
